apiVersion: v1
kind: Service
metadata:
  name: hc-bc
spec:
  type: LoadBalancer
  selector:
    app: hc-bc
  ports:
  - name: backend-port
    port: 8080
    targetPort: 8080
  - name: rxledger-port
    port: 82
    targetPort: 3002
  - name: portals-port
    port: 81
    targetPort: 5000